=== lexml/lexml-parser-projeto-lei-ws-api/src/main/xsd/ws/parser-ws.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.lexml.gov.br/parser-ws"
	xmlns:tns="http://www.lexml.gov.br/parser-ws" elementFormDefault="qualified"
	xmlns:Q1="http://www.lexml.gov.br/parser-ws" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
	jaxb:extensionBindingPrefixes="xjc" jaxb:version="1.0">

	<annotation>
		<appinfo>
			<jaxb:globalBindings generateIsSetMethod="true">
				<xjc:serializable uid="12343" />
				<xjc:superClass name="br.gov.lexml.parser.pl.ws.data.jaxb.Base" />
			</jaxb:globalBindings>
		</appinfo>
	</annotation>



	<complexType name="TipoTexto">
		<sequence>
			<element name="tipoMime" type="Q1:TipoMimeEntrada" maxOccurs="1"
				minOccurs="1"></element>
			<choice maxOccurs="1" minOccurs="1">
				<element name="TextoEmbutido" type="Q1:TipoTextoEmbutido"></element>
				<element name="TextoAnexo" type="Q1:TipoTextoAnexo"></element>
				<element name="TextoExterno" type="Q1:TipoTextoExterno"></element>
			</choice>
		</sequence>
	</complexType>

	<complexType name="TipoTextoAnexo">
		<attribute name="nomeCampo" type="string" use="required"></attribute>
	</complexType>

	<complexType name="TipoTextoExterno">
		<attribute name="href" type="anyURI" use="required"></attribute>
	</complexType>

	<complexType name="TipoTextoEmbutido">
		<simpleContent>
			<extension base="base64Binary"></extension>
		</simpleContent>
	</complexType>

	<simpleType name="TipoMimeEntrada">
		<restriction base="string">
			<enumeration value="application/msword"></enumeration>
			<enumeration value="text/rtf"></enumeration>
			<enumeration value="text/html"></enumeration>
			<enumeration value="application/xhtml+xml"></enumeration>
			<enumeration value="text/plain"></enumeration>
			<enumeration value="application/vnd.oasis.opendocument.text"></enumeration>
			<enumeration
				value="application/vnd.openxmlformats-officedocument.wordprocessingml.document"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="TipoMimeSaida">
		<restriction base="string">
			<enumeration value="application/msword"></enumeration>
			<enumeration value="text/rtf"></enumeration>
			<enumeration value="text/html"></enumeration>
			<enumeration value="application/xhtml+xml"></enumeration>
			<enumeration value="application/vnd.oasis.opendocument.text"></enumeration>
			<enumeration
				value="application/vnd.openxmlformats-officedocument.wordprocessingml.document"></enumeration>
			<enumeration value="text/xml"></enumeration>
			<enumeration value="application/zip"></enumeration>
			<enumeration value="application/pdf"></enumeration>
			<enumeration value="text/plain"></enumeration>
			<enumeration value="application/epub+zip"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="TipoMetadado">
		<sequence>
			<element name="localidade" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="autoridade" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="tipoNorma" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="descritorEvento" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<complexType name="TipoTiposDeSaidas">
		<sequence>
			<element name="tipoSaida" type="Q1:TipoTipoDeSaida"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="TipoTipoDeSaida">
		<attribute name="tipo" type="Q1:TipoSaida" use="required"></attribute>
		<attribute name="formato" type="Q1:TipoFormatoSaida" use="optional" default="EXTERNO"/>
	</complexType>

	<simpleType name="TipoFormatoSaida">
		<restriction base="string">
			<enumeration value="EXTERNO" />
			<enumeration value="EMBUTIDO" />
		</restriction>
	</simpleType>

	<simpleType name="TipoSaida">
		<restriction base="string">
			<enumeration value="DOCUMENTO_ORIGINAL"></enumeration>
			<enumeration value="PDF_ORIGINAL"></enumeration>
			<enumeration value="XML_DERIVADO"></enumeration>
			<enumeration value="ZIP_DERIVADO"></enumeration>
			<enumeration value="PDF_DERIVADO"></enumeration>
			<enumeration value="RTF_DERIVADO"></enumeration>
			<enumeration value="DOCX_DERIVADO"></enumeration>
			<enumeration value="DOCXDIFF_DERIVADO"></enumeration>
			<enumeration value="XML_REMISSOES"></enumeration>
			<enumeration value="EPUB_DERIVADO"></enumeration>
			<enumeration value="PDF_DIFF"></enumeration>
			<enumeration value="XHTML_INTERMEDIARIO"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="TipoResultado">
		<sequence>
			<element name="falhas" type="Q1:TipoFalhas" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="caracteristicas"
				type="Q1:TipoCaracteristicas" maxOccurs="1" minOccurs="1">
			</element>
			<element name="saidas" type="Q1:TipoSaidasResultado"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="digestFonte" type="Q1:TipoDigest"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="dataHoraProcessamento" type="dateTime"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="numeroDiferencas" type="int" minOccurs="0" maxOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="TipoFalhas">
		<sequence>
			<element name="falha" type="Q1:TipoFalha" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>


	<complexType name="TipoFalha">
		<sequence>
			<element name="codigoTipoFalha" type="int" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="nomeTipoFalha" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="posicao" type="string" maxOccurs="unbounded"
				minOccurs="0">
			</element>
			<element name="descricao" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="mensagemUsuario" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<complexType name="TipoCaracteristicas">
		<sequence>
			<element name="caracteristica" type="Q1:TipoCaracteristica"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<complexType name="TipoCaracteristica">
		<sequence>
			<element name="descricao" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="presente" type="boolean" maxOccurs="1"
				minOccurs="1"></element>
			<element name="suportadoLexEdit" type="boolean" maxOccurs="1"
				minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="TipoSaidasResultado">
		<sequence>
			<element name="elementoSaida" type="Q1:TipoElementoSaida"
				maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="TipoElementoSaida">
		<sequence>
			<element name="digest" type="Q1:TipoDigest" maxOccurs="1"
				minOccurs="0"></element>
			<choice maxOccurs="1" minOccurs="0">
				<element name="conteudoBinario" type="base64Binary"
					maxOccurs="1" minOccurs="0"></element>
				<element name="conteudoXML" maxOccurs="1" minOccurs="0">
					<complexType>
						<sequence>
							<any processContents="skip" namespace="##any"></any>
						</sequence>
					</complexType>
				</element>
			</choice>
		</sequence>
		<attribute name="tipoSaida" type="Q1:TipoSaida" use="required">
		</attribute>
		<attribute name="tipoMime" type="Q1:TipoMimeSaida" use="required">
		</attribute>
		<attribute name="href" type="anyURI" use="optional"></attribute>
	</complexType>

	<element name="ParserRequisicao">
		<complexType>
			<sequence>
				<element name="metadado" type="Q1:TipoMetadado"
					maxOccurs="1" minOccurs="1">
				</element>
				<element name="texto" type="Q1:TipoTexto" maxOccurs="1"
					minOccurs="1">
				</element>
				<element name="saidas" type="Q1:TipoTiposDeSaidas"
					maxOccurs="1" minOccurs="1">
				</element>
				<element name="opcoes" type="tns:OpcoesRequisicao" maxOccurs="1" minOccurs="0"></element>
			</sequence>
		</complexType>
	</element>

	<element name="ParserResultado">
		<complexType>
			<sequence>
				<element name="metadado" type="Q1:TipoMetadado" maxOccurs="1"
					minOccurs="1">
				</element>
				<element name="resultado" type="Q1:TipoResultado" maxOccurs="1"
					minOccurs="1">
				</element>
				<element name="configuracao" type="Q1:TipoConfiguracao"
					maxOccurs="1" minOccurs="1"></element>
			</sequence>
		</complexType>

	</element>


	<complexType name="TipoDigest">
		<simpleContent>
			<extension base="string"></extension>
		</simpleContent>
	</complexType>

	<complexType name="TipoConfiguracao">
		<sequence>
			<element name="componente" type="Q1:TipoConfiguracaoComponente"
				maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="TipoConfiguracaoComponente">
		<attribute name="nome" type="string" use="required"></attribute>
		<attribute name="versao" type="string" use="required"></attribute>
	</complexType>



	<complexType name="ParserProfile">
		<sequence>
			<element name="regexLocalData" type="tns:RegexList"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="regexJustificativa" type="tns:RegexList"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="regexAnexos" type="tns:RegexList"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="regexLegislacaoCitada" type="tns:RegexList"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="regexAssinatura" type="tns:RegexList"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="regexEpigrafe" type="tns:RegexList"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="regexPosEpigrafe" type="tns:RegexList"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="regexPreambulo" type="tns:RegexList"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="epigrafeObrigatoria" type="boolean"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="preEpigrafePermitida" type="boolean"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="urnFragTipoNorma" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="epigrafeHead" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="epigrafeTail" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="urnFragAutoridade" type="string"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="autoridadeEpigrafe"
				type="tns:ProfileAutoridadeEpigrafe" maxOccurs="1" minOccurs="0">
			</element>
			<element name="ementaAusente" type="boolean" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<simpleType name="RegexType">
		<restriction base="string">
			<minLength value="1"></minLength>
		</restriction>
	</simpleType>

	<complexType name="RegexList">
		<sequence>
			<element name="regex" minOccurs="1" maxOccurs="unbounded" type="tns:RegexType"></element>
		</sequence>
	</complexType>

	<complexType name="OpcoesRequisicao">
		<sequence>
			<element name="profile" type="tns:ParserProfile" maxOccurs="1" minOccurs="0"></element>
			<element name="alwaysParse" type="boolean" maxOccurs="1" minOccurs="0" default="true"/>
		</sequence>
	</complexType>

	<complexType name="ProfileAutoridadeEpigrafe">
		<sequence>
			<element name="autoridadeEpigrafeValue" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>
</schema>

=== lexml/lexml-parser-projeto-lei-ws-api/src/test/xml/result2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ParserResultado xmlns="http://www.lexml.gov.br/parser-ws" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lexml.gov.br/parser-ws ../../main/xsd/ws/parser-ws.xsd ">
  <metadado>
    <localidade>br</localidade>
    <autoridade>federal</autoridade>
    <tipoNorma>lei.federal</tipoNorma>
    <descritorEvento>>2011;178@data.evento;iniciativa;2011-10-26t10.03</descritorEvento>
  </metadado>
  <resultado>
    <falhas/>
    <caracteristicas/>
    <saidas>
    <elementoSaida tipoSaida="DOCUMENTO_ORIGINAL" tipoMime="application/msword">
    <conteudoXML>
    <teste>
    <a>asdasd</a>
    </teste>
    </conteudoXML>
    </elementoSaida>
    </saidas>
    <digestFonte>digestFonte</digestFonte>
    <dataHoraProcessamento>2001-12-31T12:00:00</dataHoraProcessamento>
  </resultado>
  <configuracao>
    <componente nome="test" versao="12312"/>
  </configuracao>
</ParserResultado>

=== lexml/lexml-parser-projeto-lei-ws-api/src/test/xml/test3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Q1:ParserRequisicao xmlns:Q1="http://www.lexml.gov.br/parser-ws" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lexml.gov.br/parser-ws ../../main/xsd/parser-ws.xsd ">
  <Q1:metadado>
    <Q1:localidade>br</Q1:localidade>
    <Q1:autoridade>senado.federal</Q1:autoridade>
    <Q1:tipoNorma>projeto.lei;pls</Q1:tipoNorma>
    <Q1:descritorEvento>2011;178@data.evento;iniciativa;2011-10-26t10.03</Q1:descritorEvento>
  </Q1:metadado>
  <Q1:texto>
    <Q1:tipoMime>text/rtf</Q1:tipoMime>
    <Q1:TextoAnexo nomeCampo=""/>
  </Q1:texto>
  <Q1:saidas>
    <Q1:tipoSaida tipo="DOCUMENTO_ORIGINAL"/>
    <Q1:tipoSaida tipo="PDF_ORIGINAL"/>
    <Q1:tipoSaida tipo="XML_DERIVADO" formato="EMBUTIDO"/>
    <Q1:tipoSaida tipo="ZIP_DERIVADO"/>
    <Q1:tipoSaida tipo="PDF_DERIVADO"/>
    <Q1:tipoSaida tipo="RTF_DERIVADO"/>
    <Q1:tipoSaida tipo="XML_REMISSOES" formato="EMBUTIDO"/>
  </Q1:saidas>
</Q1:ParserRequisicao>

=== lexml/lexml-parser-projeto-lei-ws-api/src/test/xml/parser-ws-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Q1:ParserRequisicao xmlns:Q1="http://www.lexml.gov.br/parser-ws" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lexml.gov.br/parser-ws ../../main/xsd/ws/parser-ws.xsd ">
  <Q1:metadado>
    <Q1:localidade>br</Q1:localidade>
    <Q1:autoridade>senado.federal</Q1:autoridade>
    <Q1:tipoNorma>projeto.lei;pls</Q1:tipoNorma>        
  </Q1:metadado>
  <Q1:texto>
    <Q1:tipoMime>application/vnd.openxmlformats-officedocument.wordprocessingml.document</Q1:tipoMime>    
    <Q1:TextoEmbutido>
    UEsDBBQACAgIAJqpHEcAAAAAAAAAAAAAAAALAAAAX3JlbHMvLnJlbHOtkt1KA0EMhe/7FEPuu9lW
EJGd7Y0IvROpDxBmsrtDOz9kRq1v7yCKLpRFwcskJ+d8hHS7sz+pF5bsYtCwaVpQHEy0Lowang73
6xvY9avukU9UqiRPLmVVd0LWMJWSbhGzmdhTbmLiUCdDFE+lljJiInOkkXHbttcoPz2gn3mqvdUg
e7sBdXhL/BvvOAzOsI3m2XMoFyLQcyFLhdBE4XWSaiLFca4ZJCMXDXX7obbzh6KpAYCXubZ/5bpb
4OJz4WDZLiNRSktEV/9JNFd8w7xGsfh14k+aVYezb+jfAVBLBwiYrcUK3QAAAEQCAABQSwMEFAAI
CAgAmqkcRwAAAAAAAAAAAAAAABEAAAB3b3JkL3NldHRpbmdzLnhtbEWOSxLCMAxD95wi4z0ksODT
Ie2OCwAHCK2BziR2JjYUOD1hxVLSk0b77pWieWKRkcnDcuHAIPU8jHTzcD4d5lswooGGEJnQwxsF
una2nxpB1UqJqQskzeThrpoba6W/Ywqy4IxUsyuXFLTKcrMTlyEX7lGkVlO0K+fWNoWRoK2TH+Zk
piZj6ZHUw9qB/fkDXsMj6ilcjsq5Es8QPWzc7hfb/5X2C1BLBwhvqNzvpQAAAM8AAABQSwMEFAAI
CAgAmqkcRwAAAAAAAAAAAAAAABwAAAB3b3JkL19yZWxzL2RvY3VtZW50LnhtbC5yZWxzrZFNCsIw
EIX3niLM3qZVEJGmbkRwK/UAMZ22wTYJySh6ewOKWijiwuX8fe8xL19f+45d0AdtjYAsSYGhUbbS
phFwKLfTJayLSb7HTlJcCa12gcUbEwS0RG7FeVAt9jIk1qGJk9r6XlIsfcOdVCfZIJ+l6YL7TwYU
AybbVQL8rsqAlTeHv7BtXWuFG6vOPRoakeCBbh2GSJS+QRLwqJPIAT4uP/unfG0NlfLY4dvBq/XN
xPyvP0CimOXnF56dp4VJzgfhFndQSwcI+S8wwMUAAAATAgAAUEsDBBQACAgIAJqpHEcAAAAAAAAA
AAAAAAASAAAAd29yZC9mb250VGFibGUueG1srZLPbsIwDMbve4ood0hB2jRVFDRp2mniMNgDmODS
SIlTxYGMt19oQZpGD/vDLfFnf/7ZyWzx4aw4YGDjqZKTcSEFkvZbQ7tKvq9fRo9ScATagvWElTwi
y8X8bpbK2lNkkcuJy1TJJsa2VIp1gw547FukrNU+OIj5GnYq+bBtg9fInN2dVdOieFAODMmzTfiJ
ja9ro/HZ671Dir1JQAsxT8CNaVnOz3QilQQuQ6+NQxZLTOLNO6AuQTcQGE85B7CVLPLgfRB0xLDC
WMlkaOsTjybT+6lUnSs4Y4+XmtCZdUJrom4u8QMEAxuLJ0n1KFdIq6PbeDtIcvNeTzlluNUfhuZk
mP8I8mo2GLqHEisMpu6YwMZlVi8+399KDXFPrrn3sc5/9cab+woMxEO8/XL/TfmrtZ4PPP8EUEsH
CM4sjYU4AQAAvwMAAFBLAwQUAAgICACaqRxHAAAAAAAAAAAAAAAADwAAAHdvcmQvc3R5bGVzLnht
bMVU3U/bMBB/318R+b2kIDRVFQGVIkalqkPA9n5NLo2HY3s+h1D++tkmKbQJGx/T9pLYd/H593G5
o5P7UkR3aIgrmbD9vSGLUKYq43KVsG8354MRi8iCzEAoiQlbI7GT409H9ZjsWiBF7rykcZ2wwlo9
jmNKCyyB9pRG6XK5MiVYtzWruFYm00alSOTKlyI+GA4/xyVwydoy+4edQiVPjSKV271UlbHKc55i
KOWO7w/DqhRtgTJ9DZASzG2lB66eBsuXXHC7DmBYVKbj2UoqA0vh2Do87NhxzVR6hjlUwpLfmkvT
bJtdeJ0raSmqx0Ap5wmb8yUaV17J6BoNz5lLFRNJL6QQyE6IQ8ImV9HlPLqu5MryefTl1GdTStgZ
/oDvVXQNkljsb6QHl7kDkbCDwzYypd2YALlqY9oOTq+2b3soBtOFDy155qAVfDBb+INxQyzepat3
d+GbZ+9NNu4IF3rG3WXX2qmrwcDKgC789SE1yxK28EaJILuEElvoTThQ+nkezIw3AOpxzTNVT50D
Ron2SA6CsBGm0tq4vptUVl2sdYFyo5M1FTaEm1r/zdBUCWVaXOCg/lufgwWvtekCwQ+Jjk9tPGBa
AmH2VfZ5KPHetvEbtz5V2fpFd28R9cJ99EheQ8oD1yW6vxq9BEOPDXKLxg2xg+Gb/fQW9NvZZD72
e456bBt9RP2NYrvy+0T0pOVvDGjEeVJTcIlXlR97ofWaiEc6Ys/E3pL6sE/q95Kac7IdQiHYx2W7
abbmUNfyHoPei3IK2ndGB2gb/5PuPe3dTqe503tRla756IVO9739hk7v7Uv++JzSq4fLe6WayQzv
O0I9Rv+aTB80vV3R8S9QSwcIDknKb4ACAAAMCQAAUEsDBBQACAgIAJqpHEcAAAAAAAAAAAAAAAAR
AAAAd29yZC9kb2N1bWVudC54bWztWk1vHLkRvedXEHOygZFGsmTZmqy0EFbehYFdSYic3DndnBk6
3awOyZ5Z+eRrzrnuAmv4YCSAT0YuOab/iX9JXpH9NZJWUNa7PnQCCOqeYbNIPr56VcWeL778Ps/E
SlmnyRyNdrd3RkKZhFJtFkejP774euvpSDgvTSozMupodKXc6Mvj332xnqaUlLkyXsCCcVM6GpXW
TF2yVLl0W7lOLDma+62E8inN5zpR9WVU97BHo6X3xXQyqTttU6EM2uZkc+nx0S4msctpPdbk0c7O
wcSqTHrM1y114Rprq7vGX+VZ89z6PqOuyaaFpUQ5ByDyLI6bS21aM7s791gw22l7FPcZObVy3Rty
cyKnsbGz6G6YbKexjWnU6AUrsLe7c83e5VIWqrO2+DRr31gqi8Zantxntbm0fy4LRqzAjs50pv1V
WHg3qd39T5vVdcx+mT3mT55Mny8MWTnL4AgwJHh2o2P4wozSK74W4d+FDZdLf5UpsZ6uZHY0OuNV
Z6MJt1h+YNJd6w72Rtt66o8vLL1UnkSqxLdKi5TEpTISF0Ni/8mTMTdgmo+3uZePfaPV32BCv6lx
nv5J5pWVQoa1YoWH2zuHB2GNu4f83ymv8pml+M3hY/EgguLEhbRehxvKqvdeJ+QejoXqm3q8sx9M
7e3cYupJbUo68SxTunpX/VOxhUJiPto4r32prUDzXKWYY3yAOxfNyEU78jA241x8dX72zR+eXV6e
i7OTr56fn518iwUnVnkppoNY4on122KXxMmvRbhCOgf+fg5weISVXkCQQEtsikt0KlkgnFqU2nhw
P6xud+tkGJv18fUPG+u4e1Ox7G1xStoJKgVCt+s7Kjy4ekvCqtJou+WUUHnn129pDNn4SykzXIvq
gxOulCKhWgTCE1AWIF6oxOsV21lo58GSAhYYeRIvrJ6VRmbissSXmmyQFY/dYqu+lLZ6A5s5b5eY
k8P/Mpei+pfRCQi0sCrXcTL1vKs3VsthCMu/3wWfKzIsNWf0q5/66G+IqieWZPwZHs1hWxj5BfaL
xLw0CfJAyalhgCkLt/AH1v25TlUGl2itDQvBR0DQsatbyRBKUYCQyq4aDBG1UoARAVD8WZaeDIFW
Qb9ahFkqFoG2IZz1NmIQWHHiN3WFTJC01RCpEQO4x7KfWN2Rrs9BmuFDothLq59cq6mOyWelm4oh
YHP8XHx8/Tfhqg+dJtZ0sOxBPTxaukCzOr1L1VwbHTTQ3Kl5vx8GXBGvvveEEMI3mxEEyKwinkAi
l4apBERRuUKXMo0E3o0Zsrx6b3SOgFMArX3xAFEHuD4U0pAbCmYRtGt0CnR7A7+ybWSt3rNI+erv
eDaVnpFiMqUBw+o9pcFJrZKZftWqHBPSrJSp8/Ge0g8Fvz/dAp8P4MkZZHtR/QNRUAojQyzMBCet
ZeeiLjyqDEKtNkuuHOWdnjoI0Wd93ydxDsK4pMwLq2OOgKWn2hXkfBAsDeQcCTAUsMSQIBNpucAJ
+LayF3zVqVwBUtUl2MhbODWkhKyN2zBmrsY0vLAEHUVOpwJNUUNiJ2qWWrXC7hBnNa6ehRPP8WSc
SiKL0vNNyOD3D9GwUmkXqLRBfohCw97IW9GYqEzNWMATyvSi7mQwg0fiQVpK9xAq1BS4vbimxtH3
+DAmYwAEL0G+ajUKlGIhcwmQVGGk0mt2RRtTsbSfqQ4jd2AaPSZxJsVSoxAATIrXDVIxspFSXBiK
B2X+8EadMb7mtBAqr03M/Hnf+tnruBG+em/edmUcQ+0wCme+hgNIHVGqdzIPe4oa5+bgnwX/GqID
9rRCpbpR6DY7+Nm0/v56VAuYDIeEsQMb6IjbHESTG0aZG8NlUn0oOFOXXGdSVta6T7lMmQGgAbab
EOYQBbjdx6x+RawqfFd9sAt0cZGwmZ61+9BGChYLNlfmd1QEGxweSEjdhHhTqlHaO48C3bPD5qW5
DsFGujIIPG6vkNq8jZmleroEhGpuBWppq67TagOv7WFUSpC5JyxzLTlqRfaWAbqZShw0xVEQr6Zs
jMfJMgRZcrot1TMIphScF5BN+XxfXmdd7Oj6sRusRdUQQNcDOXIGcE8//WSIv0ZNGo4+3Ka0dWf0
nNFxl1S/ikd5CDeh1O8QHvOuZqXTK9U87XiMubJ84IJUiLKlFJsRL5EGgVB6crftWS5fQrR9LFDQ
c2MPkQQg92RJbs4YZUCiXTsaS+tisQmAQjyM5jlUsgG2Jxf8vrb9OhuHzEMyMrARIsRY0MyHoult
PelUafBzHE6RfDdi6MkT5SqLelNxJbJEjhCDIN7PHhIdkrhAQh9SEGTCDCxowgh4TjlsBM8uiOEO
5yC9HW4pAxqGqt+OuYgQL0v29kSWTo57lA5P17F3Q0E/vv5xGCIaTuYfbbxu+YUv5cJbFnGP1x8H
9L/2+uMUaH3de0c5hMXf7p8nzQZv3zNkXIvZzfsx8DH91V45/z8sfYawdJ+4NAzJvODjAgSEOcV3
g8inq7+G0yA+LBXh1zS3vsDo8z6+xWzOc/6rQ1QOPoMAMojFHolnHHvZhcES+AHYF6IIypd46Bw4
hBK7nLUcvz3FcSrxtfGrop2fUd/7C5A6zrBYXL5Cy/potLt7yD9rWk+XuD94uve0eeA7xK/1NFNz
zw/t7fMzVi+WvY9LBT+wR6Md/uCp6FrmRL5tmZH3lHeNi9LXjfVQZ2X+Ik51nsN8qhLdYslEurDk
m3XMZebqRXgs6RRlXsI/umvaM/tixs2TDohJ80OoSffrwOP/AFBLBwjonLMBFQgAAGIoAABQSwME
FAAICAgAmqkcRwAAAAAAAAAAAAAAABAAAABkb2NQcm9wcy9hcHAueG1snY9PS8MwHIbvfooSdm0T
u1LHSDMU8TRwhyreSpb82kaaPyTp6L69UWH27PHhfXl4X3pY9JRdwAdlTYPuC4IyMMJKZYYGvbUv
+Q5lIXIj+WQNNOgKAR3YHT1568BHBSFLBhMaNMbo9hgHMYLmoUixSUlvveYxoR+w7Xsl4NmKWYOJ
uCSkxrBEMBJk7m5C9GvcX+J/pdKK733hvb265GO0tZFPrdLAthT/AX10blKCx3SeHdXZw+uPDVdF
VWyLcnNUZl66j13d1VW2KnRp7SeIiCuiyeZpVpPMS4rXOnring+euzGw8oHiFSa4nWVfUEsHCMF2
HhHtAAAAggEAAFBLAwQUAAgICACaqRxHAAAAAAAAAAAAAAAAEQAAAGRvY1Byb3BzL2NvcmUueG1s
lZLBTsMwDIbvPEWVe5um1VCJ2kwCtBNICIaYuEWp10U0aZRk6/b2pGXrBtqFo/P//uzYLud71UY7
sE52ukIkSVEEWnS11E2F3peLuECR81zXvO00VOgADs3ZTSkMFZ2FF9sZsF6CiwJIOypMhTbeG4qx
ExtQ3CXBoYO47qziPoS2wYaLL94AztL0FivwvOae4wEYm4mIjshaTEizte0IqAWGFhRo7zBJCD57
PVjlriaMyoVTSX8wcNV6Eif33snJ2Pd90uejNfRP8Or56W38aiz1MCoBiJXHRqiwwD3UUQDQn3In
5SN/eFwuEMtSMovTIs6KJSloekfz9LPEf/IHIG25brZhbMz4+P518JyfpoIq7G4t/1GRZHSWX1Q8
AdiwYws7OZwGIyW+DMfo9wGwb1BLBwh61EsuMAEAAEwCAABQSwMEFAAICAgAmqkcRwAAAAAAAAAA
AAAAABMAAABbQ29udGVudF9UeXBlc10ueG1svZTNTsMwEITvfYrIV5Q4cEAIJe0BiSP0EM7I2JvE
Iv6R15T27Vm3NEKAGkELl0iWZ+abta1Ui7UZshUE1M7W7LwoWQZWOqVtV7OH5ja/Yov5rGo2HjAj
rcWa9TH6a85R9mAEFs6DpZ3WBSMiLUPHvZDPogN+UZaXXDobwcY8pgw2r+4JF7SCbClCvBMGasYf
AwzIi/Rl2c3OkJg1E94PWopI/fjKqk+0/J2UnFsN9trjGQkY/5706oLiCDHShFgk4Y94rm21BOXk
iyFLkdJ8cBIQKc8MxT55ssJu4jGI5P82fUuERjwNcPrxx+jpK4ibAf7iAra5k/iPB3/aAuOOEdoe
6kHCZXAeOQGPrgFrcipQOXXxEKI+fAYjW7rwi2ewf3fJ/ZU4q/j2fzF/A1BLBwgZGhCDLQEAAF4E
AABQSwECFAAUAAgICACaqRxHmK3FCt0AAABEAgAACwAAAAAAAAAAAAAAAAAAAAAAX3JlbHMvLnJl
bHNQSwECFAAUAAgICACaqRxHb6jc76UAAADPAAAAEQAAAAAAAAAAAAAAAAAWAQAAd29yZC9zZXR0
aW5ncy54bWxQSwECFAAUAAgICACaqRxH+S8wwMUAAAATAgAAHAAAAAAAAAAAAAAAAAD6AQAAd29y
ZC9fcmVscy9kb2N1bWVudC54bWwucmVsc1BLAQIUABQACAgIAJqpHEfOLI2FOAEAAL8DAAASAAAA
AAAAAAAAAAAAAAkDAAB3b3JkL2ZvbnRUYWJsZS54bWxQSwECFAAUAAgICACaqRxHDknKb4ACAAAM
CQAADwAAAAAAAAAAAAAAAACBBAAAd29yZC9zdHlsZXMueG1sUEsBAhQAFAAICAgAmqkcR+icswEV
CAAAYigAABEAAAAAAAAAAAAAAAAAPgcAAHdvcmQvZG9jdW1lbnQueG1sUEsBAhQAFAAICAgAmqkc
R8F2HhHtAAAAggEAABAAAAAAAAAAAAAAAAAAkg8AAGRvY1Byb3BzL2FwcC54bWxQSwECFAAUAAgI
CACaqRxHetRLLjABAABMAgAAEQAAAAAAAAAAAAAAAAC9EAAAZG9jUHJvcHMvY29yZS54bWxQSwEC
FAAUAAgICACaqRxHGRoQgy0BAABeBAAAEwAAAAAAAAAAAAAAAAAsEgAAW0NvbnRlbnRfVHlwZXNd
LnhtbFBLBQYAAAAACQAJADwCAACaEwAAAAA=
    </Q1:TextoEmbutido>
  </Q1:texto>
  <Q1:saidas>    
    <Q1:tipoSaida formato="EXTERNO" tipo="XML_DERIVADO"/>
  </Q1:saidas>
  <Q1:opcoes>    
    <Q1:alwaysParse>true</Q1:alwaysParse>
  </Q1:opcoes>
</Q1:ParserRequisicao>
